# Generated by Django 2.2.2 on 2020-10-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('idno', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=30)),
                ('salary', models.FloatField()),
            ],
        ),
    ]
